sonar.projectKey=library-reservation-system-frontend
sonar.projectName=Library Reservation System Frontend

sonar.sources=src
sonar.exclusions=node_modules/**,build/**,dist/**,.next/**

sonar.host.url=http://localhost:9000
