services:

  mariadb:
    container_name: mariadb
    image: library-reservation-system-database:latest
    build:
      context: ./backend/database
      dockerfile: Dockerfile
    environment:
      MARIADB_DATABASE: metbook
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "13306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "${DB_USERNAME}", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: backend
    image: library-reservation-system-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/metbook
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_MAIL_USERNAME: ${MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${MAIL_PASSWORD}
    depends_on:
      mariadb:
        condition: service_healthy
  
  frontend:
    container_name: frontend
    image: library-reservation-system-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - "3000:80"
  
volumes:
  mariadb-data:
