services:

  mariadb:
    image: mariadb:lts-ubi9
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: metbook
    ports:
      - "27017:27017"
    volumes:
      - mariadb-data:/var/lib/mysql

  library-reservation-system-backend:
    image: library-reservation-system-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mariadb
  
  library-reservation-system-frontend:
    image: library-reservation-system-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - "3000:80"
  
volumes:
  mariadb-data:
