DROP DATABASE IF EXISTS MetBook;
CREATE DATABASE MetBook;
USE MetBook;

CREATE TABLE USERS(
UserId INT AUTO_INCREMENT PRIMARY KEY,
Email VARCHAR(100) UNIQUE NOT NULL,
Nickname VARCHAR(50) NOT NULL,
PasswordHash VARCHAR(255) NOT NULL,
CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
Role ENUM('user', 'admin') NOT NULL DEFAULT 'user'
);

CREATE TABLE GENRE(
Genre VARCHAR(50) NOT NULL,
PRIMARY KEY (Genre)
);

CREATE TABLE LANGUAGE(
Language VARCHAR(100) NOT NULL,
PRIMARY KEY (Language)
);

CREATE TABLE BOOK(
ISBN INT PRIMARY KEY,
BookTitle VARCHAR(100) NOT NULL,
PublishingYear INT NOT NULL,
ImageName VARCHAR(100),
Description TEXT NOT NULL,
Genre VARCHAR(50) NOT NULL,
Language VARCHAR(100) NOT NULL,
FOREIGN KEY (Genre) REFERENCES GENRE(Genre),
FOREIGN KEY (Language) REFERENCES LANGUAGE(Language)
);

CREATE TABLE AUTHOR(
FirstName VARCHAR(100) NOT NULL,
LastName VARCHAR(100) NOT NULL,
AuthorId INT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE LOAN(
LoanID INT AUTO_INCREMENT PRIMARY KEY,
CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
DueDate DATETIME NOT NULL,
Returndate DATETIME NULL,
UserId INT NOT NULL,
ISBN INT NOT NULL,
FOREIGN KEY (UserId) REFERENCES USERS(UserId),
FOREIGN KEY (ISBN) REFERENCES BOOK(ISBN)
);

CREATE TABLE RESERVATION(
ReservationID INT AUTO_INCREMENT PRIMARY KEY,
CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
Status ENUM('active', 'not_active') NOT NULL DEFAULT 'active',
UserID INT NOT NULL,
ISBN INT NOT NULL,
FOREIGN KEY (UserId) REFERENCES USERS(UserId),
FOREIGN KEY (ISBN) REFERENCES BOOK(ISBN)
);

CREATE TABLE WRITES(
AuthorId INT NOT NULL,
ISBN INT NOT NULL,
PRIMARY KEY (AuthorId, ISBN),
FOREIGN KEY (AuthorId) REFERENCES AUTHOR(AuthorId),
FOREIGN KEY (ISBN) REFERENCES BOOK(ISBN)
);

CREATE TABLE FAVORITE
(
UserId INT NOT NULL,
ISBN INT NOT NULL,
PRIMARY KEY (UserId, ISBN),
FOREIGN KEY (UserId) REFERENCES USERS(UserId),
FOREIGN KEY (ISBN) REFERENCES BOOK(ISBN)
);