pipeline {
    agent any

    /* tools {
        jdk 'JDK 21' // java set to jenkins settings
        maven 'Maven3' // maven set to jenkins settings
    } */

    environment {
        DOCKERHUB_CREDENTIALS_ID = 'docker_hub' // docker credentials in jenkins settings
        DOCKERHUB_REPO = 'library-reservation-system'
        DOCKER_IMAGE_TAG = 'latest'
        BACKEND_DIRECTORY = 'backend'
        FRONTEND_DIRECTORY = 'frontend'
    }

    stages {
        // only use "Check" stage with "Pipeline script" in jenkins, comment out if using the Jenkinsfile in repository
        /* stage ('Check') {
            steps {
                // can change branch if needed, useful for testing features
                git url: 'https://github.com/Nurha20-24/library-reservation-system.git', credentialsId: 'GitHub-pat', branch: 'jenkins-integration'
            }
        } */

        stage('Build') {
            agent {
                docker {
                    image 'maven:3.9.6-eclipse-temurin-21'
                    args '-v maven-cache:/root/.m2 --user root'
                    reuseNode true
                }
            }
            steps {
                dir(BACKEND_DIRECTORY) {
                    sh 'mvn clean install'
                }
            }
        }

        stage('Run Tests') {
            agent {
                docker {
                    image 'maven:3.9.6-eclipse-temurin-21'
                    args '-v maven-cache:/root/.m2 --user root'
                    reuseNode true
                }
            }
            steps {
                dir(BACKEND_DIRECTORY) {
                    sh 'mvn test'
                }
            }
        }

        stage ('Generate and Publish Code Coverage Report'){
            agent {
                docker {
                    image 'maven:3.9.6-eclipse-temurin-21'
                    args '-v maven-cache:/root/.m2 --user root'
                    reuseNode true
                }
            }
            steps {
                dir(BACKEND_DIRECTORY) {
                    sh 'mvn jacoco:report'
                }
            }
            post {
                always {
                    jacoco()
                }
            }
        }

        stage('Build Docker Image and Push Docker Image to Docker Hub') {
            steps {
                sh 'docker --version'
                sh 'docker ps'

                withCredentials([usernamePassword(credentialsId: DOCKERHUB_CREDENTIALS_ID, usernameVariable: 'DOCKERHUB_USERNAME', passwordVariable: 'DOCKERHUB_PASSWORD')]) {
                    sh """
                        docker build -t $DOCKERHUB_USERNAME/${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG} ${BACKEND_DIRECTORY}/
                        echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
                        docker push $DOCKERHUB_USERNAME/${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}
                        docker logout
                    """
                }
            }
        }

    }

    /* stage('Diagnostics') {
        steps {
            sh 'java -version'
            sh 'mvn --version'
            sh 'echo $JAVA_HOME'
            sh 'docker version'
            sh "docker build -t ${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG} ${BACKEND_DIRECTORY}/"
        }
    } */

}