sonar.projectKey=library-reservation-system-backend
sonar.projectName=Library Reservation System Backend

sonar.sources=src
sonar.java.binaries=target/classes
sonar.coverage.exclusions=**/src/test/java/**

sonar.host.url=http://localhost:9000