INSERT INTO author (first_name, last_name)
VALUES
('Jere', 'Käpyaho'),
('Nikhil', 'Abraham'),
('Rami', 'Juvonen'),
('Gayle', 'Laakmann McDowell'),
('Dave', 'Thomas'),
('Andy', 'Hunt'),
('Carol', 'Vorderman'),
('Rachel', 'Ignotofsky'),
('Alexander', 'Jung'),
('Alex', 'Banks'),
('Eve', 'Porcello'),
('Helen', 'Mortimer'),
('Jon', 'Woodcock'),
('J.K.', 'Rowling'),
('Rebecca', 'Yarros'),
('Sylvain', 'Neuvel'),
('Brian', 'Aldiss'),
('David', 'Wingrove'),
('Isaac', 'Asimov'),
('J.R.R.', 'Tolkien'),
('Satu', 'Rämö'),
('Marie-Hélène', 'Baylac'),
('Kitty', 'Ferguson'),
('Simon', 'Adams'),
('Iain', 'Simons'),
('James', 'Newman'),
('Tom', 'Phillips'),
('Tuula', 'Karjalainen');
