INSERT INTO book
(isbn, book_title, book_title_ja, book_title_ar, publishing_year, image_name, description, description_ja, description_ar, genre, language)
VALUES

('9789528083030',
 'Selkeästi Python',
 'やさしく学ぶPython',
 'بايثون ببساطة',
 2024,
 '9789528083030.jpg',
 'Selkeästi Python on helposti sulava suomenkielinen opas ohjelmointiin Python-kielellä. Kirja esittelee Python-ohjelmointia helppojen esimerkkien avulla, ja johdattelee kokeilemaan erilaisia tietojenkäsittelyn tehtäviä omalla tietokoneella. Kirja on tarkoitettu kaikille Pythonista kiinnostuneille, ja se soveltuu itseopiskeluun sekä oppilaitosten kurssikirjaksi.',
 '「やさしく学ぶPython」は、Pythonプログラミングをわかりやすく解説したフィンランド語の入門書です。本書は簡単な例を通してPythonを紹介し、自分のコンピュータでさまざまな情報処理の課題に挑戦できるよう導きます。Pythonに興味のあるすべての人を対象としており、独学にも教育機関の教材としても適しています。',
 'كتاب "بايثون ببساطة" هو دليل فنلندي سهل الفهم لتعلم البرمجة بلغة بايثون. يقدّم الكتاب البرمجة باستخدام أمثلة بسيطة، ويشجع القارئ على تجربة مهام مختلفة في معالجة البيانات على جهازه الشخصي. هذا الكتاب مناسب لكل من يهتم ببايثون، سواء للتعلم الذاتي أو ككتاب دراسي.',
 'nonfiction',
 'finnish'),

('9781118951309',
 'Coding For Dummies',
 'ダミーのためのコーディング',
 'البرمجة للمبتدئين',
 2015,
 '9781118951309.jpg',
 'Build your Python coding skills step-by-step and have fun doing it! Learn to program simple games, apps, and more. Gradually build knowledge from functions to space treasure game projects. Hints and helpful tips assist with common problems and encourage creative thinking.',
 'Pythonのコーディングスキルを段階的に楽しく身につけましょう！シンプルなゲームやアプリなどの作り方を学びます。関数の基礎から宇宙をテーマにした宝探しゲームプロジェクトまで、徐々に知識を積み上げていきます。ヒントや役立つアドバイスが、よくある問題の解決を助け、創造的な思考を促します。',
 'طوّر مهاراتك في برمجة بايثون خطوة بخطوة واستمتع أثناء التعلم! تعلّم إنشاء ألعاب بسيطة وتطبيقات وغير ذلك. قم ببناء معرفتك تدريجيًا بدءًا من الدوال وصولًا إلى مشاريع مثل لعبة البحث عن الكنز في الفضاء. توفر النصائح والإرشادات المساعدة في حل المشكلات الشائعة وتشجع على التفكير الإبداعي.',
 'nonfiction',
 'english'),

('9789528001454',
 'Ohjelmistoprojektin sudenkuopat ja miten ne vältetään',
 'ソフトウェアプロジェクトの落とし穴とその回避方法',
 'مشاكل مشاريع البرمجيات وكيفية تجنبها',
 2018,
 '9789528001454.jpg',
 'Tiesitkö, että suurin osa ohjelmistoprojekteista epäonnistuu? Jopa kokeneet ammattilaiset kokevat ohjelmistoprojektien hallinnan hankalaksi. Digitalisaation myötä ohjelmistotyön määrä on kuitenkin jatkuvassa kasvussa. Tässä helppotajuinen selviytymisopas kaikille ohjelmistoprojektien parissa työskenteleville.',
 'ソフトウェアプロジェクトの大半が失敗していることをご存知ですか？経験豊富な専門家でさえ、プロジェクト管理の難しさに直面しています。デジタル化の進展によりソフトウェア開発の需要は増え続けています。本書は、ソフトウェアプロジェクトに関わるすべての人のための、わかりやすい実践ガイドです。',
 'هل تعلم أن معظم مشاريع البرمجيات تفشل؟ حتى المحترفون ذوو الخبرة يواجهون صعوبة في إدارة هذه المشاريع. ومع تطور الرقمنة، يزداد العمل في مجال البرمجيات باستمرار. يقدم هذا الكتاب دليلًا مبسطًا لكل من يعمل في مشاريع البرمجيات.',
 'nonfiction',
 'finnish'),

('9780984782857',
 'Cracking the Coding Interview',
 'コーディング面接完全対策',
 'دليل اجتياز مقابلات البرمجة',
 2015,
 '9780984782857.jpg',
 'Now in the 6th edition, the book gives you the interview preparation you need to get the top software developer jobs. Includes 189 programming interview questions and answers.',
 '第6版となる本書は、トップクラスのソフトウェア開発職に就くために必要な面接対策を提供します。189問のプログラミング面接問題とその解答を収録しています。',
 'في نسخته السادسة، يقدّم هذا الكتاب التحضير اللازم لاجتياز مقابلات العمل للحصول على أفضل وظائف تطوير البرمجيات. يحتوي على 189 سؤالًا وإجابة لمقابلات البرمجة.',
 'nonfiction',
 'english'),

('9780135957059',
 'The Pragmatic Programmer',
 '達人プログラマー',
 'المبرمج العملي',
 2020,
 '9780135957059.jpg',
 'The Pragmatic Programmer is one of those rare tech books you''ll read, re-read, and read again over the years. Covers software development, programming techniques, and practical advice.',
 '『達人プログラマー』は、何度も読み返したくなる数少ない技術書のひとつです。ソフトウェア開発、プログラミング技術、そして実践的なアドバイスを幅広くカバーしています。',
 'يُعد كتاب "المبرمج العملي" من الكتب التقنية النادرة التي ستعود لقراءتها مرارًا على مر السنين. يغطي تطوير البرمجيات وتقنيات البرمجة ويقدم نصائح عملية.',
 'nonfiction',
 'english'),

('9780241286869',
 'Computer Coding Python Projects for Kids',
 '子どものためのPythonプログラミングプロジェクト',
 'مشاريع بايثون للأطفال',
 2017,
 '9780241286869.jpg',
 'Build your Python coding skills step-by-step and have fun doing it! Learn to program simple games, apps, and more. Gradually build knowledge from functions to space treasure game projects. Hints and helpful tips assist with common problems and encourage creative thinking.',
 'Pythonのスキルを楽しく段階的に学びましょう。ゲームやアプリの作成を通して、基礎から応用まで知識を広げます。役立つヒントが問題解決と創造力を促します。',
 'تعلّم البرمجة بلغة بايثون بطريقة ممتعة خطوة بخطوة. أنشئ ألعابًا وتطبيقات وتطوّر تدريجيًا مع نصائح تساعدك على حل المشكلات وتشجع الإبداع.',
 'children',
 'english'),

('9781526365132',
 'The History of the Computer',
 'コンピュータの歴史',
 'تاريخ الحاسوب',
 2022,
 '9781526365132.jpg',
 'Explore the fascinating history of the computer and the people who made them, from ancient counting systems to AI, space travel, and wearable tech. Accessible information, fun facts and discussion starters for children.',
 '古代の計算方法からAI、宇宙旅行、ウェアラブル技術に至るまで、コンピュータとそれを作り上げた人々の魅力的な歴史を探ります。子ども向けにわかりやすい情報、楽しい豆知識、議論のきっかけが含まれています。',
 'استكشف التاريخ المثير للحاسوب والأشخاص الذين صنعوه، من أنظمة العد القديمة إلى الذكاء الاصطناعي والسفر إلى الفضاء والتقنيات القابلة للارتداء. يقدم معلومات سهلة وحقائق ممتعة ومواضيع للنقاش للأطفال.',
 'children',
 'english'),
('9789811681929',
'Machine Learning: The Basics',
'機械学習：基礎',
'تعلم الآلة: الأساسيات',
2022,
'9789811681929.jpg',
'Machine learning (ML) has become commonplace in everyday life. This book explains the underlying principles and computational implementations, including model adaptation, prediction, and minimizing loss.',
'機械学習（ML）は日常生活の中で一般的なものとなっています。本書では、モデルの適応、予測、損失の最小化などを含む基礎原理と計算的実装について解説します。',
'أصبح تعلم الآلة جزءًا شائعًا من حياتنا اليومية. يشرح هذا الكتاب المبادئ الأساسية والتطبيقات الحاسوبية، بما في ذلك تكييف النماذج والتنبؤ وتقليل الخسارة.',
'nonfiction',
'english'),

('9781492051725',
'Learning React: Modern Patterns for Developing React Apps',
'React学習：最新パターンでのアプリ開発',
'تعلم React: أنماط حديثة لتطوير التطبيقات',
2020,
'9781492051725.jpg',
'Learn to build efficient React applications. Covers functional programming, component lifecycle, best practices, and modern ECMAScript features. Suitable for web developers and software engineers.',
'効率的なReactアプリケーションの構築方法を学びます。関数型プログラミング、コンポーネントのライフサイクル、ベストプラクティス、最新のECMAScript機能をカバーしています。Web開発者やソフトウェアエンジニアに適しています。',
'تعلّم كيفية بناء تطبيقات React بكفاءة. يغطي البرمجة الوظيفية ودورة حياة المكونات وأفضل الممارسات وميزات ECMAScript الحديثة. مناسب لمطوري الويب ومهندسي البرمجيات.',
'nonfiction',
'english'),

('9780192786982',
'Coding',
'コーディング',
'البرمجة',
2024,
'9780192786982.jpg',
'Learn coding through games and activities designed for children. Focus on sequencing, puzzles, and developing coding vocabulary. Illustrated with engaging scenes.',
'子ども向けに設計されたゲームやアクティビティを通してコーディングを学びます。順序立て、パズル、プログラミング用語の習得に焦点を当てています。魅力的なイラストで説明されています。',
'تعلّم البرمجة من خلال ألعاب وأنشطة مصممة للأطفال. يركّز على التسلسل وحل الألغاز وتطوير مفردات البرمجة، مع رسوم توضيحية جذابة.',
'children',
'english'),

('9789513241667',
'Kivaa koodausta: opetellaan ohjelmointia',
'楽しいコーディング：プログラミングを学ぼう',
'برمجة ممتعة: لنتعلم البرمجة',
2016,
'9789513241667.jpg',
'Opetellaan Python-ohjelmointia hauskojen tehtävien avulla. Tietotekniikan perusteita lapsille selkokielisesti ja havainnollisesti.',
'楽しい課題を通してPythonプログラミングを学びます。子ども向けに情報技術の基礎をわかりやすく説明しています。',
'تعلّم برمجة بايثون من خلال مهام ممتعة. يقدّم أساسيات تكنولوجيا المعلومات للأطفال بطريقة سهلة وواضحة.',
'children',
'finnish'),

('9789513111465',
'Harry Potter ja viisasten kivi',
'ハリー・ポッターと賢者の石',
'هاري بوتر وحجر الفيلسوف',
1998,
'9789513111465.jpg',
'Harry Potter on mielestään ihan tavallinen poika. Tosin hän asuu huoltajiensa luona portaiden alla olevassa kaapissa. Harryn elämä muuttuu täysin, kun hän saa 11-vuotispäivänään merkillisen kirjeen. Se on kutsu Tylypahkan velhojen ja noitien kouluun. Harrylle avautuu kokonaan uusi maailma, johon kuuluvat velhot, noidat, yksisarviset ja lohikäärmeet. Harry saa tietää olevansa velhojen sukua! Viisasten kivi on ensimmäinen teos kaiken ikäisten suosion saavuttaneessa Harry Potter -sarjassa.',
'ハリー・ポッターは自分を普通の少年だと思っています。しかし彼は階段下の物置で暮らしています。11歳の誕生日に不思議な手紙を受け取り、彼の人生は一変します。それはホグワーツ魔法魔術学校への招待状でした。魔法使いや魔女、ユニコーンやドラゴンが存在する新しい世界が広がります。自分が魔法使いの家系であることを知るのです。本作は大人気シリーズの第1作です。',
'يعتقد هاري بوتر أنه فتى عادي، لكنه يعيش في خزانة تحت الدرج. تتغير حياته تمامًا عندما يتلقى رسالة غامضة في عيد ميلاده الحادي عشر، تدعوه إلى مدرسة هوجورتس للسحر. يكتشف عالمًا جديدًا مليئًا بالسحرة والمخلوقات السحرية، ويعلم أنه ينتمي لعائلة من السحرة. هذا هو الجزء الأول من السلسلة الشهيرة.',
'fantasy',
'finnish'),

('9789513162641',
'Harry Potter ja salaisuuksien kammio',
'ハリー・ポッターと秘密の部屋',
'هاري بوتر وغرفة الأسرار',
2011,
'9789513162641.jpg',
'Harryn Potterin ankea kesäloma Dursleyn perheen luona päättyy, kun Weasleyn veljekset hakevat hänet lentävällä Anglialla. Sekopäinen Dobby-tonttu on varoittanut Harrya palaamasta takaisin Tylypahkan velhojen ja noitien kouluun, mutta mikään ei saisi Harrya jäämään pois. Toinen lukuvuosi Tylypahkassa alkaa odottamattomasti, ja salaperäiset tapahtumat saavat Harryn, Ronin ja Hermionen tutkimaan 50 vuotta vanhaa arvoitusta. Vain Harry kuulee uhkaavan äänen, joka kuiskuttaa kuolemasta läpi koulun seinien.',
'ダーズリー家での退屈な夏休みは、ウィーズリー兄弟が空飛ぶ車で迎えに来たことで終わります。屋敷しもべ妖精ドビーは学校に戻るなと警告しますが、ハリーは戻る決意をします。ホグワーツでの2年目、奇妙な出来事が起こり、ハリー、ロン、ハーマイオニーは50年前の謎を追います。ハリーだけが不気味な声を聞きます。',
'تنتهي عطلة هاري البائسة عندما يأتيه أصدقاءه بسيارة طائرة. يحذره دوبي من العودة، لكنه يصر. في عامه الثاني، تبدأ أحداث غامضة ويحقق مع أصدقائه في لغز قديم، بينما يسمع صوتًا مرعبًا لا يسمعه غيره.',
'fantasy',
'finnish'),

('9780747560777',
'Harry Potter and the Prisoner of Azkaban',
'ハリー・ポッターとアズカバンの囚人',
'هاري بوتر وسجين أزكابان',
2002,
'9780747560777.jpg',
'Join Harry Potter on the magical journey of a lifetime in this large print edition of the third book in J.K. Rowling''s series. Dementors patrol Hogwarts and Sirius Black is on the loose. Harry faces omens of death and challenges in Divination class, navigating magic and dark forces with his friends.',
'シリーズ第3作では、ハリーは人生を変える魔法の冒険に挑みます。ディメンターがホグワーツを巡回し、シリウス・ブラックが脱獄しています。死の予兆や占いの授業の試練に直面しながら、仲間と共に闇の力に立ち向かいます。',
'في الجزء الثالث، يواجه هاري مغامرة سحرية خطيرة، حيث تحرس الديمينتورز المدرسة ويهرب سيريوس بلاك. يواجه نذر الموت وتحديات جديدة مع أصدقائه.',
'fantasy',
'english'),

('9780747550990',
'Harry Potter and the Goblet of Fire',
'ハリー・ポッターと炎のゴブレット',
'هاري بوتر وكأس النار',
2000,
'9780747550990.jpg',
'In his fourth year at Hogwarts, Harry faces darkening events and a fate orchestrated by his worst enemy. With spells, potions, and Divination lessons, Harry navigates friendships, magic, and challenges with wit and emotional depth.',
'ホグワーツでの4年目、ハリーは暗い出来事と宿敵によって仕組まれた運命に直面します。呪文や薬、占いを通して友情と試練に立ち向かいます。',
'في عامه الرابع، يواجه هاري أحداثًا مظلمة ومصيرًا خطيرًا، ويتعامل مع التحديات بالسحر والصداقة.',
'fantasy',
'english'),

('9780747569602',
'Harry Potter and the Order of the Phoenix',
'ハリー・ポッターと不死鳥の騎士団',
'هاري بوتر وجماعة العنقاء',
2003,
'9780747569602.jpg',
'Harry Potter faces new dangers at Hogwarts as Voldemort returns. With the help of friends and a secret order, he must navigate magic, mystery, and dark forces in this fifth adventure of the series.',
'ヴォルデモートの復活により、ハリーは新たな危険に直面します。仲間と秘密組織の助けを借り、魔法と闇の力に立ち向かいます。',
'يواجه هاري أخطارًا جديدة مع عودة فولدمورت، ويقاتل مع أصدقائه ضد القوى المظلمة.',
'fantasy',
'english'),

('9780349436999',
 'Fourth Wing',
 'フォース・ウィング',
 'الجناح الرابع',
 2023,
 '9780349436999.jpg',
 'Violet Sorrengail must survive Basgiath War College, a deadly training ground for dragon riders, where friends, enemies, and lovers all have agendas. Dragons, battles, and secrets abound in this epic fantasy adventure.',
 'ヴァイオレット・ソレンゲイルは、ドラゴン騎手の訓練場であるバスギアス戦争大学を生き抜かなければならない。そこでは友人も敵も恋人もそれぞれの思惑を抱えている。壮大なファンタジーアドベンチャーの中で、ドラゴン、戦い、そして秘密が渦巻く。',
 'يجب على فيوليت سورينغيل أن تنجو من كلية باسغياث الحربية، ميدان التدريب المميت لفرسان التنين، حيث يملك الأصدقاء والأعداء والمحبون أجنداتهم الخاصة. التنانين والمعارك والأسرار تملأ هذه الملحمة الفانتازية المثيرة.',
 'fantasy',
 'english'),

('9780349437026',
 'Iron Flame',
 'アイアン・フレイム',
 'اللهب الحديدي',
 2023,
 '9780349437026.jpg',
 'The thrilling sequel to Fourth Wing, Violet Sorrengail faces higher stakes at Basgiath War College. Secrets, sacrifices, and battles intensify, testing her courage and wit against a new powerful enemy.',
 '『フォース・ウィング』の続編となる本作では、ヴァイオレット・ソレンゲイルがバスギアス戦争学院でさらに大きな危険に直面します。秘密や犠牲、戦いは激しさを増し、新たな強敵に対して彼女の勇気と機知が試されます。',
 'في هذا الجزء المثير، تواجه فيوليت مخاطر أكبر في أكاديمية باسغياث العسكرية. تتصاعد الأسرار والتضحيات والمعارك، مما يختبر شجاعتها وذكاءها أمام عدو قوي جديد.',
 'fantasy',
 'english'),

('9789510514986',
 'Onyx Storm',
 'オニキス・ストーム',
 'عاصفة الأونيكس',
 2025,
 '9789510514986.jpg',
 'The third installment of the Empyrean series finds Violet Sorrengail in deadlier peril than ever, facing dragons, battles, and secrets in a richly imagined fantasy world.',
 'シリーズ第3作では、ヴァイオレット・ソレンゲイルがこれまで以上に危険な状況に置かれ、ドラゴンや戦い、数々の秘密に満ちた壮大なファンタジー世界で奮闘します。',
 'في الجزء الثالث من السلسلة، تواجه فيوليت أخطارًا أشد من أي وقت مضى، في عالم خيالي غني مليء بالتنانين والمعارك والأسرار.',
 'fantasy',
 'english'),

('9789511389576',
 'Tulevaisuuden historia',
 '未来の歴史',
 'تاريخ المستقبل',
 2021,
 '9789511389576.jpg',
 'Tummanpuhuva satiiri naisista, jotka mahdollistavat kehityksen, ja miehistä, jotka yrittävät pysäyttää heidät. Mian perhe on muokannut ihmiskunnan historiaa yli 99 sukupolven ajan. Ihmishenki on ollut halpa, kun päämääränä on ollut avaruus. Mian tehtävä on salakuljettaa Wernher Von Braun natsi-Saksasta amerikkalaisten käsiin ja varmistaa avaruusvarustelun tulevaisuus. Apua tarvitsevat myös venäläiset, jotta suurvaltojen välinen jännite onnistuu lopulta saattelemaan ihmisen tähtiin. Mian perhe ei ole kuitenkaan ainoa, joka yrittää vaikuttaa historian kulkuun. Armoton vihollinen seuraa kannoilla jatkuvasti. Keitä Mian perhe on ja mistä he tulevat? Entä keitä ovat heitä jahtaavat miehet?',
 '発展を可能にする女性たちと、それを阻もうとする男性たちを描いたダークな風刺作品。ミアの一族は99世代以上にわたり人類の歴史を操ってきました。宇宙進出という目的のために人命は軽視されてきました。ミアの任務はヴェルナー・フォン・ブラウンをナチス・ドイツからアメリカへ密かに移送し、宇宙開発競争の未来を確保することです。さらにロシア側にも協力し、大国間の緊張が最終的に人類を星へ導くように仕向けます。しかしミアの一族だけが歴史を動かしているわけではありません。無慈悲な敵が常に彼らを追い続けています。ミアの一族とは何者なのか？彼らはどこから来たのか？そして彼らを追う者たちは誰なのか？',
 'سخرية مظلمة عن النساء اللواتي يدفعن عجلة التطور والرجال الذين يحاولون إيقافهن. قامت عائلة ميا بتشكيل تاريخ البشرية لأكثر من 99 جيلًا. كانت حياة الإنسان رخيصة عندما كان الهدف هو الوصول إلى الفضاء. مهمة ميا هي تهريب فيرنر فون براون من ألمانيا النازية إلى الأمريكيين لضمان مستقبل سباق الفضاء. كما يجب مساعدة الروس حتى يؤدي التوتر بين القوى العظمى في النهاية إلى إيصال البشرية إلى النجوم. لكن عائلة ميا ليست الوحيدة التي تحاول التأثير على مجرى التاريخ. عدو لا يرحم يلاحقهم باستمرار. من هي عائلة ميا؟ ومن أين جاءوا؟ ومن هم الرجال الذين يطاردونهم؟',
 'science fiction',
 'finnish'),

('0575039434',
 'Trillion Year Spree: The History of Science Fiction',
 'SF文学1兆年の歴史',
 'تاريخ الخيال العلمي عبر تريليون عام',
 1986,
 '0575039434.jpg',
 'A comprehensive history of science fiction literature by Brian W. Aldiss, covering its evolution and impact, with contributions from David Wingrove.',
 'ブライアン・W・オールディスによるSF文学の包括的な歴史書で、その発展と影響を解説しています。デイヴィッド・ウィングローヴも寄稿しています。',
 'كتاب شامل عن تاريخ أدب الخيال العلمي بقلم براين ألديس، يشرح تطوره وتأثيره، بمساهمة ديفيد وينغروف.',
 'science fiction',
 'english'),

('9780008117498',
 'Foundation',
 'ファウンデーション',
 'المؤسسة',
 2016,
 '9780008117498.jpg',
 'Isaac Asimov''s classic series about Hari Seldon''s Foundations, established to preserve knowledge and shape the fate of the galaxy during the decline of the Galactic Empire.',
 'アイザック・アシモフによる名作シリーズで、銀河帝国の衰退期に知識を保存し銀河の運命を導くために設立された「ファウンデーション」を描いています。',
 'سلسلة كلاسيكية لإسحاق أسيموف عن مؤسسات هاري سيلدون التي أُنشئت للحفاظ على المعرفة وتحديد مصير المجرة أثناء انهيار الإمبراطورية.',
 'science fiction',
 'english'),

('9780261103252',
 'The Lord of the Rings',
 '指輪物語',
 'سيد الخواتم',
 2007,
 '9780261103252.jpg',
 'Frodo Baggins embarks on a perilous journey across Middle-earth to destroy the One Ring. Magic, battles, friendship, and courage define this epic fantasy saga.',
 'フロド・バギンズは、一つの指輪を破壊するため中つ国を旅する危険な冒険に出ます。魔法、戦い、友情、勇気が描かれる壮大なファンタジー作品です。',
 'ينطلق فرودو باجينز في رحلة خطيرة عبر الأرض الوسطى لتدمير الخاتم الواحد. السحر والمعارك والصداقة والشجاعة تشكل هذه الملحمة الخيالية.',
 'fantasy',
 'english'),

('9789510479209',
 'Hildur',
 'ヒルドゥル',
 'هيلدور',
 2022,
 '9789510479209.jpg',
 'Satu Rämö vie lukijansa Islannin vuonojen hämärään – eikä ruumiilta vältytä. Lapsuudessaan traumatisoitunut rikosetsivä ja kadonneiden lasten yksikön päällikkö Hildur Rúnarsdóttir taistelee omaa ahdistustaan vastaan surffaamalla Atlantin kylmissä vesissä. Hildurin työpariksi saapuu suomalainen poliisiharjoittelija Jakob Johanson, joka on lähtenyt Islantiin pakoon omaa hankalaa elämäntilannettaan. Pian Hildur ja Jakob ovat keskellä omituista rikosvyyhtiä, kun vuosikymmeniä hämärässä olleiden salaisuuksien sumuverho alkaa vähitellen hälvetä. Hildur aloittaa päähenkilönsä nimeä kantavan, nordic noirin hengelle uskollisen dekkarisarjan, jossa on ripaus islantilaista mystiikkaa.',
 'サトゥ・ラモは読者をアイスランドのフィヨルドの暗く神秘的な世界へと導きます――そこでは死体も避けられません。幼少期にトラウマを抱えた刑事であり、行方不明の子ども捜索班の責任者ヒルドゥル・ルーナルスドッティルは、冷たい大西洋でサーフィンをすることで自身の不安と向き合っています。彼女の相棒としてやって来るのは、困難な私生活から逃れるためにアイスランドへ来たフィンランド人の警察研修生ヤコブ・ヨハンソンです。やがて二人は奇妙な事件の渦中に巻き込まれ、何十年も隠されてきた秘密が少しずつ明らかになっていきます。本作は、北欧ノワールの精神に忠実でありながら、アイスランドの神秘を織り交ぜた、主人公の名を冠する新たなミステリーシリーズの幕開けです。',
 'تأخذ الكاتبة ساتو رامو القارئ إلى أجواء مظلمة في فيوردات آيسلندا – حيث لا تخلو الأحداث من الجثث. هيلدور رونارسدوتير، محققة جنائية ورئيسة وحدة الأطفال المفقودين، تعاني من صدمات طفولتها وتحاول مواجهة قلقها من خلال ركوب الأمواج في مياه الأطلسي الباردة. ينضم إليها شريك جديد، المتدرب الشرطي الفنلندي ياكوب يوهانسون، الذي جاء إلى آيسلندا هربًا من حياته المعقدة. سرعان ما يجد الاثنان نفسيهما وسط لغز جنائي غريب، حيث تبدأ أسرار ظلت مخفية لعقود في الانكشاف تدريجيًا. تمثل هذه الرواية بداية سلسلة بوليسية بروح النوردك نوار مع لمسة من الغموض الآيسلندي.',
 'crime fiction',
 'finnish'),

('9789523129580',
 'Agatha Christie: arvoituksellinen elämä',
 'アガサ・クリスティ：謎めいた人生',
 'أجاثا كريستي: حياة غامضة',
 2020,
 '9789523129580.jpg',
 'Tuore kattava elämäkerta osoittaa, että Agatha Christien elämä oli yhtä vaiheikasta ja jännittävää kuin hänen kuuluisilla henkilöhahmoillaan neiti Marplella ja Hercule Poirotilla. Rikosten kuningatar oli seikkailija, joka ei piitannut sovinnaisuudesta, vaikka muuten oli elämänasenteiltaan varsin "viktoriaaninen". Alkuperäiset ranskalaiset lähteet tuovat uutta tietoa Agatha Christien elämästä. Agatha syntyi Millerien perheen kolmantena lapsena vuonna 1890. Perheen taloudellisten vaikeuksien takia hän ei saanut lainkaan muodollista koulutusta. Ensimmäisen rikostarinansa hän kuitenkin kirjoitti jo pikkutyttönä, ja hänestä tuli lopulta William Shakespearen jälkeen kaikkien aikojen myydyin kirjailija. Ensimmäisen maailmansodan sytyttyä vuonna 1914 Agatha ryhtyi työskentelemään sairaanhoitajana. Sairaalan apteekissa hän oppi myös paljon myrkyistä, joilla tulisi olemaan merkittävä osa monissa hänen romaaneissaan. Joulukuussa 1914 24-vuotias Agatha Miller meni naimisiin Kuninkaallisten ilmavoimien upseerin Archibald Christien kanssa. Avioliiton hajoaminen toisen naisen takia vuonna 1926 oli Agathalle kova isku. Hän katosi tietymättömiin kymmeneksi päiväksi koko Englannin etsiessä häntä. Sanomalehdet - ja varsinkin keltainen lehdistö - tarttuivat hanakasti aiheeseen ja yksityinen avio-ongelma muodostui valtakunnan ykkösuutiseksi. Agatha Christien toinen avioliitto Max Mallowanin kanssa muutti elämän suunnan. Christie vietti paljon aikaa Irakissa ja Syyriassa osallistuen kaivauksiin ja kirjoittaen samalla suuren määrän salapoliisikirjallisuuden klassikoita.',
 '本書は、アガサ・クリスティの人生が、ミス・マープルやエルキュール・ポアロといった彼女の有名な登場人物たちと同じくらい波乱に満ち、魅力的であったことを明らかにする最新の包括的伝記です。「ミステリーの女王」は型破りな冒険家でもあり、一般的な慣習にとらわれない人物でしたが、その人生観はどこかヴィクトリア朝的でもありました。フランスの新資料に基づき、彼女の人生に新たな光が当てられています。1890年、ミラー家の三女として生まれた彼女は、家庭の経済的事情により正式な教育を受けることができませんでしたが、幼い頃から物語を書き始め、やがてウィリアム・シェイクスピアに次ぐ史上2番目のベストセラー作家となりました。第一次世界大戦中には看護師として働き、薬局で毒物の知識を得たことが後の作品に大きな影響を与えました。1914年には空軍将校アーチボルド・クリスティと結婚しましたが、1926年に離婚し、その際に彼女が10日間行方不明になった事件は英国中の話題となりました。その後、考古学者マックス・マローワンとの再婚により人生は新たな方向へ進み、中東での発掘に参加しながら数々の名作を執筆しました。',
 'سيرة حديثة وشاملة تُظهر أن حياة أجاثا كريستي كانت مليئة بالأحداث والإثارة مثل شخصياتها الشهيرة الآنسة ماربل وهيركيول بوارو. كانت "ملكة الجريمة" مغامِرة لا تهتم بالتقاليد رغم أن نظرتها للحياة كانت تحمل طابعًا فيكتوريًا. تكشف مصادر فرنسية جديدة تفاصيل إضافية عن حياتها. وُلدت عام 1890 في عائلة ميلر، ولم تحصل على تعليم رسمي بسبب ظروف عائلتها، لكنها بدأت الكتابة في سن مبكرة وأصبحت لاحقًا ثاني أكثر كاتبة مبيعًا بعد شكسبير. خلال الحرب العالمية الأولى عملت ممرضة واكتسبت معرفة بالسموم أثرت على أعمالها. تزوجت عام 1914 من أرشيبالد كريستي، وانتهى الزواج عام 1926 في حادثة شهيرة اختفت خلالها عشرة أيام. لاحقًا غير زواجها من عالم الآثار ماكس مالوان مسار حياتها، حيث شاركت في حفريات في الشرق الأوسط وكتبت العديد من رواياتها الشهيرة.',
 'biography',
 'finnish'),

('9780593068632',
 'Stephen Hawking: his life and work',
 'スティーブン・ホーキング：その人生と業績',
 'ستيفن هوكينغ: حياته وأعماله',
 2011,
 '9780593068632.jpg',
 'Stephen Hawking''s contributions to physics and cosmology literally changed our understanding of the universe. This captivating biography introduces his life and greatest scientific contributions, with accessible explanations on his theories surrounding general relativity, quantum mechanics, the science of black holes, and his pursuit of the ''Theory of Everything''. This biography is gives wonderful insight into Hawking''s extraordinary achievements and how his attitude to life and work were the true driver of his success.',
 'スティーブン・ホーキングの物理学と宇宙論への貢献は、文字通り私たちの宇宙理解を変えました。この魅力的な伝記は彼の生涯と最大の科学的貢献を紹介し、一般相対性理論、量子力学、ブラックホールの科学、そして「万物の理論」の追求に関する彼の理論について分かりやすく解説しています。この伝記は、ホーキングの並外れた業績と、彼の人生と仕事に対する姿勢が成功の真の原動力であったことを素晴らしい洞察を与えてくれます。',
 'مساهمات ستيفن هوكينغ في الفيزياء وعلم الكونيات غيرت فهمنا للكون حرفيا. تقدم هذه السيرة الساحرة حياته وأعظم إسهاماته العلمية، مع شروحات سهلة الفهم حول نظرياته المتعلقة بالنسبية العامة، ميكانيكا الكم، علم الثقوب السوداء، وسعيه ل''نظرية كل شيء''. تقدم هذه السيرة الذاتية نظرة رائعة على إنجازات هوكينغ الاستثنائية وكيف كان موقفه من الحياة والعمل هو المحرك الحقيقي لنجاحه.',
 'biography',
 'english'),

('9780241600948',
 'History: the definitive visual guide',
 '歴史：決定版ビジュアルガイド',
 'التاريخ: الدليل البصري الشامل',
 2023,
 '9780241600948.jpg',
 'This lavishly illustrated visual encyclopedia tells the story of our world in depth and detail from the dawn of civilization to the present day. Charting human endeavour from every angle, History chronicles the significant events, ground-breaking ideas, political forces, and technological advances that have shaped our planet. Every historical episode is explored and explained with the help of stunning images that bring the authoritative text to life. Important points in history, from the battle of Hastings and the storming of the Bastille to D-Day and 9/11, have clear but concise coverage, together with profiles of influential figures, such as Julius Caesar, Cleopatra, and Nelson Mandela. With its broad-themed approach to important historical events, this book shows that ours is a history with genes and viruses, not just battle and treaties - and the stories and biographies of men and women from every corner of the globe who have shaped today''s world reaffirm that History is the story of humankind in which everyone has a part to play. ',
 'この豪華な図版付きビジュアル百科事典は、文明の黎明期から現代に至るまで、私たちの世界の物語を深く詳細に語っています。あらゆる角度から人類の努力を描き、『History』は地球を形作った重要な出来事、画期的なアイデア、政治的力、技術革新を記録しています。すべての歴史的エピソードが、権威あるテキストに命を吹き込む美しい画像を用いて探求・解説されています。ヘイスティングズの戦いやバスティーユ襲撃、Dデイや9/11に至るまで、歴史の重要な出来事は明確かつ簡潔に扱われており、ユリウス・シーザー、クレオパトラ、ネルソン・マンデラといった影響力のある人物のプロフィールも含まれています。重要な歴史的出来事を幅広くテーマに扱うこの本は、私たちの歴史が単なる戦いや条約ではなく、遺伝子とウイルスの歴史であることを示しています。そして、世界中の男女が今日の世界を形作ってきた人々の物語や伝記は、歴史こそが人類の物語であり、誰もが役割を果たす役割であることを再確認させています。',
 'تروي هذه الموسوعة البصرية المصورة بغنى قصة عالمنا بعمق وتفصيل من فجر الحضارة وحتى يومنا هذا. يرسم التاريخ الجهود البشرية من كل زاوية، ويوثق الأحداث المهمة والأفكار الرائدة والقوى السياسية والتطورات التكنولوجية التي شكلت كوكبنا. يتم استكشاف كل حلقة تاريخية وشرحها بمساعدة صور مذهلة تحيي النص الموثوق. نقاط مهمة في التاريخ، من معركة هاستينغز واقتحام الباستيل إلى يوم الإنزال وأحداث 11 سبتمبر، لها تغطية واضحة لكنها موجزة، إلى جانب ملفات شخصيات مؤثرة مثل يوليوس قيصر، كليوباترا، ونيلسون مانديلا. بنهجه الواسع للأحداث التاريخية المهمة، يظهر هذا الكتاب أن تاريخنا يحتوي على الجينات والفيروسات، وليس فقط المعارك والمعاهدات -وتؤكد قصص وسير الرجال والنساء من كل ركن من أركان العالم الذين شكلوا عالم اليوم أن التاريخ هو قصة البشرية التي يلعب فيها الجميع دورهم.',
 'history',
 'english'),

('9781787390645',
 'A history of videogames',
 'ビデオゲームの歴史',
 'تاريخ ألعاب الفيديو',
 2018,
 '9781787390645.jpg',
 'Forget about bits and bytes, data and code and see the world of videogames through the most unique, important and sometimes downright ordinary stuff on the planet. From the humble audio cassette to out-of-this-world virtual reality, this is the story of videogames - told through objects! The curators of the UK''s award-winning National Videogame Arcade take you on a journey through joysticks and microchips, Game Boys and cuddly toys, guitars, drums and Ocarinas as they tell the story of how videogames are made, played and loved. Whatever your interest in gaming - casual Pokemon player, GTA expert, medal-winning FIFA champion of anything in-between - this is the book for you.',
 'ビットやバイト、データやコードのことは忘れて、世界で最もユニークで重要、時にはごく普通のものを通してビデオゲームの世界を見てください。質素なオーディオカセットから、まさに現実離れしたバーチャルリアリティまで、これはビデオゲームの物語です――物を通して語られるのです!英国の受賞歴のあるナショナル・ビデオゲーム・アーケードのキュレーターたちが、ジョイスティックやマイクロチップ、ゲームボーイやぬいぐるみ、ギター、ドラム、オカリナを通じて、ビデオゲームがどのように作られ、遊び、愛されるかの物語を語ります。ゲームに興味がある方、カジュアルなポケモンプレイヤー、GTAのエキスパート、メダル獲得のFIFAチャンピオンなど、どんなゲームでも、この本はあなたにぴったりの本です。',
 'انس البتات والبايتات، والبيانات، والشيفرة، وانظر عالم ألعاب الفيديو من خلال أكثر الأشياء تميزا وأهمية وأحيانا عادية على الكوكب. من شريط الصوت المتواضع إلى الواقع الافتراضي الغريب، هذه هي قصة ألعاب الفيديو - تروى من خلال الأشياء! يأخذك القيمون في صالة الألعاب الوطنية الحائزة على جوائز في المملكة المتحدة في رحلة عبر عصي التحكم والشرائح الإلكترونية، وأجهزة جيم بويز، والألعاب اللطيفة، والجيتارات، والطبول، والأوكارينا، وهم يروون قصة كيفية صنع ولعب وحب ألعاب الفيديو. مهما كان اهتمامك بالألعاب - لاعب بوكيمون عادي، خبير في GTA، بطل FIFA الحائز على الميداليات في أي شيء بينهما - هذا هو الكتاب المناسب لك.',
 'history',
 'english'),

('9781472259059',
 'Humans: a brief history of how we f*cked it all up',
 '人類のしくじり簡史',
 'تاريخ أخطاء البشرية',
 2019,
 '9781472259059.jpg',
 '''This book is brilliant. Utterly, utterly brilliant. Apart from the epilogue, which is idiotic'' Jeremy Clarkson. ''F*cking brilliant'' Sarah Knight. AN EXHILARATING JOURNEY THROUGH THE MOST CREATIVE AND CATASTROPHIC F*CK-UPS OF HUMAN HISTORY. In the seventy thousand years that modern human beings have walked this earth, we''ve come a long way. Art, science, culture, trade - on the evolutionary food chain, we''re real winners. But, frankly, it''s not exactly been plain sailing, and sometimes - just occasionally - we''ve managed to really, truly, quite unbelievably f*ck things up. From Chairman Mao''s Four Pests Campaign, to the American Dustbowl; from the Austrian army attacking itself one drunken night, to the world''s leading superpower electing a reality TV mogul as President... it''s pretty safe to say that, as a species, we haven''t exactly grown wiser with age. So, next time you think you''ve really f*cked up, this book will remind you: it could be so much worse...',
 '「この本は素晴らしい。まったく、まったくもって素晴らしい。エピローグを除けば、それは馬鹿げている、ジェレミー・クラークソン。『クソみたいに素晴らしい』サラ・ナイト。人類史上最も創造的で壊滅的な失敗を巡る刺激的な旅。現代人がこの地球を歩んできて7万年の間に、私たちは大きく進歩しました。芸術、科学、文化、貿易――進化の食物連鎖の中で、私たちは本当の勝者です。しかし正直なところ、決して順調な状況ではなく、時には本当に信じられないほど物事を台無しにしてしまうこともあります。毛主席の四害虫キャンペーンからアメリカのダストボウルまで、ある夜、オーストリア軍が自らを攻撃し、世界有数の超大国がリアリティ番組の大物を大統領に選出するまで...人類として、年齢を重ねても賢くなったわけではないと言っても間違いない。だから、次に本当にやらかしたと思うとき、この本は思い出させてくれる:もっとひどいこともあり得る...',
'هذا الكتاب رائع. عبقري تماما، بشكل لا يصدق. باستثناء الخاتمة، التي هي غبية لجيريمي كلاركسون. ''رائعة جدا'' سارة نايت. رحلة مثيرة عبر أكثر الأخطاء إبداعا وكارثية في تاريخ البشرية. في السبعين ألف سنة التي سار فيها البشر المعاصرون على هذه الأرض، قطعنا شوطا طويلا. الفن، العلم، الثقافة، التجارة - في السلسلة الغذائية التطورية، نحن فائزون حقيقيون. لكن، بصراحة، لم تكن الأمور سهلة تماما، وأحيانا - فقط بين الحين والآخر - تمكنا من إفساد الأمور بشكل لا يصدق حقا، حقا. من حملة الرئيس ماو "الآفات الأربعة"، إلى "وعاء الغبار الأمريكي"؛ من الجيش النمساوي الذي هاجم نفسه في ليلة سكران، إلى انتخاب القوة العظمى الكبرى في العالم ليكون رئيسا لرجل تلفزيون الواقع... من الآمن إلى حد كبير القول إننا، كنوع، لم نصبح أكثر حكمة مع التقدم في العمر. لذا، في المرة القادمة التي تعتقد فيها أنك أخطأت حقا، سيذكرك هذا الكتاب: كان يمكن أن يكون أسوأ بكثير...',
 'history',
 'english'),

('9789513169633',
 'Tove Jansson: tee työtä ja rakasta',
 'トーベ・ヤンソン：働き、愛せ',
 'توفه يانسون: اعمل واحب',
 2013,
 '9789513169633.jpg',
 'Tove Jansson (1914-2001) oli monilahjakkuus - kuvataiteilija, kirjailija, kuvittaja, käsikirjoittaja, laulujen sanoittaja ja miltei mitä vain. Tuula Karjalaisen kirjoittama uutuuselämäkerta asettaa Tove Janssonin pitkän, värikkään ja tuotteliaan elämän osaksi 1900-luvun historiaa ja osoittaa, miten Janssonin elämä ja taide nivoutuivat tiiviisti toisiinsa ja miten esimerkiksi Muumilaakso ja sen asukkaat syntyivät toisen maailmansodan aikoihin, jolloin kirjailijan itsensä oli paettava julmaa aikaa mielikuvitukseensa, jonnekin lempeämpään maailmaan.',
 'トーベ・ヤンソン は多才なアーティストであり、視覚芸術家、作家、イラストレーター、脚本家、作詞家、そしてほぼあらゆる分野に携わってきました。トゥーラ・カルヤライネンによる新しい伝記は、トーヴェ・ヤンソンの長く多彩で実り多い人生を20世紀の歴史の一部として位置づけ、ヤンソンの人生と芸術が密接に結びついていたこと、例えばムーミンバレーとその住民たちが第二次世界大戦中に誕生したことを示している。著者自身が残酷な時代から逃れ、より穏やかな場所へと逃れなければならなかった時代に。',
 'توف يانسون كانت فنانة متعددة المواهب - فنانة بصرية، كاتبة، رسامة، كاتبة سيناريو، كاتبة كلمات للأغاني وأي شيء تقريبا. السيرة الجديدة التي كتبتها تولا كارجالاينن تضع حياة توفي يانسون الطويلة والملونة والمنتجة كجزء من تاريخ القرن العشرين، وتظهر كيف كانت حياة يانسون وفنها متشابكتين ارتباطا وثيقا، وكيف، على سبيل المثال، ولد وادي مومين وسكانها خلال الحرب العالمية الثانية، عندما اضطرت المؤلفة نفسها للهروب من ذلك الزمن القاسي إلى خيالها، في مكان أكثر لطفا.',
 'biography',
 'finnish');
